# Generated by Django 5.1.1 on 2024-09-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trnx_uuid', models.CharField(max_length=100)),
                ('sender_pub_key', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('trnx_hash', models.CharField(max_length=100)),
                ('trnx_signature', models.BinaryField()),
                ('parent_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.block')),
            ],
        ),
    ]
