# Generated by Django 5.1.1 on 2024-09-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_pub_key',
            field=models.CharField(default='dfeef', max_length=100),
            preserve_default=False,
        ),
    ]
