# Generated by Django 5.1.1 on 2024-09-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_wallet_transaction_receiver_pub_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='prev_block_hash',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_pub_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_pub_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trnx_hash',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trnx_uuid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(max_length=200),
        ),
    ]
