# Generated by Django 5.1.1 on 2024-09-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_alter_block_hash_alter_block_prev_block_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('verified', 'verified')], default='pending', max_length=20),
        ),
    ]
