# Generated by Django 5.1.1 on 2024-09-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_alter_transaction_parent_block_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trnx_hash',
            new_name='trxn_hash',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='trnx_signature',
            new_name='trxn_signature',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='trnx_uuid',
            new_name='trxn_uuid',
        ),
    ]
